//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Admin
    {
        public int AdminId { get; set; }
        [DisplayName("AdminEmail")]
        [Required]
        public string AdminEmail { get; set; }
        [DisplayName("AdminPassword")]
        [Required]
        [DataType(DataType.Password)]
        public string AdminPassword { get; set; }

        public string LoginErrorMessage { get; set; }

        [Required]
        public string UserCheck { get; set; }
        public IEnumerable<SelectListItem> User { get; set; }
    }
}
